### ISSUE TITLE
[Request] Sending events to space / all objects

### ISSUE THREAD

**Issue by Qbz23** [Azurelol/StratusFramework#1]
I'm not sure the current framework supports a way to send out events to all objects in a level that have subscribed to an event type, this would be a nice feature to have so that global type events don't need to store tons of object references on their dispatchers

**Comment by Azurelol** [comment]
Oh, it does! You can dispatch and connect to events in the "global" Scene object like so:

Scene.Dispatch<T>(new T());
Scene.Connect<T>(OnT);

There's an EventsSample script that shows how it's done; perhaps I should have pointed out to the examples more explicitly...
